site_name: Open Science Labs
site_url: https://opensciencelabs.org

docs_dir: pages
site_dir: build

theme:
  name: null
  custom_dir: "theme/"
  features:
    - content.code.copy
  palette:
    primary: indigo

extra_css:
  - css/style.css
  - css/index.css

extra_javascript:
  - js/bundle.js
  - js/search.js
  - js/index.json

nav:
  - Home: "index.md"
  - Dashboards: "dashboards/index.md"
  - Mentors: "mentors/index.md"
  - Donate: "donate/index.md"

markdown_extensions:
  - toc:
      permalink: " #"
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - include-markdown
