name: osl-ds-web
channels:
  - nodefaults
  - conda-forge
dependencies:
  - python 3.12
  - pip
  - poetry
  - nodejs # used by semantic-release
  - shellcheck
  - pip:
      # distlib issue
      - paginate==0.5.6
